all: destination_migration_agent

destination_migration_agent: destination_migration_agent.c
	gcc -Wall -o destination_migration_agent destination_migration_agent.c

.PHONY: clean
clean:
	rm destination_migration_agent
